### ISSUE TITLE
CSS blockquote/cite

### ISSUE THREAD

**Issue by malukenho** [Ocramius/extremely-defensive-php#1]
## Preview

![screenshot 2015-05-29 07 28 47](https://cloud.githubusercontent.com/assets/3275172/7880846/c2438d0c-05d3-11e5-8428-23b196d59390.png)
## Copy/Paste:

``` css
/** Personal stylezation */
.reveal section blockquote {
  background: #f9f9f9;
  border-left: 10px solid #ccc;
  margin: 1.5em 10px;
  padding: 0.5em 10px;
  quotes: "\201C""\201D""\2018""\2019";
}

.reveal section blockquote:before {
  color: #ccc;
  content: open-quote;
  font-size: 4em;
  line-height: 0.1em;
  margin-right: 0.25em;
  vertical-align: -0.4em;
}

.reveal section blockquote p { display: inline; }
.reveal section blockquote cite:before { content: ' - '; }

.reveal section blockquote cite {
  display: block;
  width: 100%;
  text-align: right;
  font-size: 20px;
}
```

ping @Ocramius
